name: bawo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  google_fonts: ^2.1.0
  flutter_svg: 0.22.0
  intl: ^0.17.0
  multi_image_picker: ^4.7.14
  flutter_vector_icons: ^1.0.0
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  dio: ^4.0.0
  page_view_indicators: ^2.0.0
  http: ^0.13.3
  dartz: ^0.9.2
  url_launcher: ^6.0.9
  #sqlcool:
  #sqflite: any
  permission_handler: ^8.1.4+2
  image_picker: ^0.8.3+1
  inview_notifier_list: ^2.0.0
  flutter_cache_manager: ^3.1.2
  timeago: ^3.1.0
  pull_to_refresh:
  android_intent: any

  moor_flutter:
  # Service locator
  get_it:
  fluttertoast: ^8.0.8
  #for Touch ID / Face ID and Fingerprint Authentication
  local_auth:
  share: ^2.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  json_annotation: ^4.0.0
  pretty_dio_logger: ^1.1.1
  scrollable_positioned_list: ^0.1.10
  page_transition: ^2.0.2
  location: ^4.3.0
  pin_code_fields: ^7.3.0
  device_info_plus: ^2.1.0
  shared_preferences: ^2.0.6
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  flutter_markdown: ^0.6.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  logging: ^1.0.0
  json_serializable: ^4.0.3
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/EuclidCircularABold.ttf
          weight: 700
        - asset: assets/fonts/EuclidCircularABoldItalic.ttf
        - asset: assets/fonts/EuclidCircularAItalic.ttf
        - asset: assets/fonts/EuclidCircularALight.ttf
        - asset: assets/fonts/EuclidCircularALightItalic.ttf
        - asset: assets/fonts/EuclidCircularAMedium.ttf
        - asset: assets/fonts/EuclidCircularAMediumItalic.ttf
        - asset: assets/fonts/EuclidCircularARegular.ttf
        - asset: assets/fonts/EuclidCircularASemiBold.ttf
        - asset: assets/fonts/EuclidCircularASemiBoldItalic.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
